import test from 'node:test';
import assert from 'node:assert/strict';
import {importJobUrl} from '../lib/job-import.ts';
const url='https://jobs.dayforcehcm.com/en-US/example/CANDIDATEPORTAL/jobs/2512';
const job={jobPostingId:2512,jobReqId:405,jobTitle:'Senior Designer',jobPostingContent:{jobDescriptionHeader:'<p>About our team</p>',jobDescription:'<p>Lead accessible product design.</p><ul><li>Coach designers.</li></ul>',jobDescriptionFooter:'<p>Equal opportunity employer.</p>'},hasVirtualLocation:true,postingLocations:[{formattedAddress:'United States'}],isoCurrencyRegion:'USD',jobPostingAttributes:[{name:'PayType',value:'Salary'},{name:'HiringMinRate',value:157450},{name:'HiringMaxRate',value:174950}],postingStartTimestampUTC:'2026-09-11T04:00:00Z'};
function html(overrides={}){return `<title>Job Details | Dayforce Jobs</title><script id="__NEXT_DATA__" type="application/json">${JSON.stringify({props:{pageProps:{jobData:{...job,...overrides},dehydratedState:{queries:[{queryKey:['site-info'],state:{data:{clientNamespace:'example',candidateCorrespondenceClientName:'Example Education Talent Team'}}}]}}}})}</script>`;}
async function extract(t,body,strict=false,target=url){t.mock.method(globalThis,'fetch',async()=>new Response(body,{headers:{'Content-Type':'text/html'}}));return importJobUrl(target,strict);}
test('Dayforce extracts complete content and salary from page props',async t=>{const j=await extract(t,html(),true);assert.equal(j.title,'Senior Designer');assert.equal(j.company,'Example Education');assert.equal(j.location,'Remote · United States');assert.equal(j.salaryMin,157450);assert.equal(j.salaryMax,174950);assert.match(j.description,/About our team[\s\S]*Coach designers[\s\S]*Equal opportunity employer/);assert.equal(j.verification,'employer');assert.equal(j.requisitionId,'405');});
test('Dayforce does not infer remote or salary when fields are missing',async t=>{const j=await extract(t,html({hasVirtualLocation:false,postingLocations:[{formattedAddress:'London'}],jobPostingAttributes:[]}));assert.equal(j.location,'London');assert.equal(j.salaryMin,undefined);});
test('Dayforce rejects mismatched IDs and incomplete page data',async t=>{await assert.rejects(extract(t,html({jobPostingId:99})),/complete Dayforce/);await assert.rejects(extract(t,html({jobPostingContent:{}})),/complete Dayforce/);await assert.rejects(extract(t,'<title>Job Details | Dayforce Jobs</title>'),/complete Dayforce/);});
test('Dayforce honors expiry in discovery and preserves explicit manual import',async t=>{const body=html({postingExpiryTimestampUTC:'2020-01-01T00:00:00Z'});await assert.rejects(extract(t,body,true),/expired/);assert.equal((await extract(t,body)).validThrough,'2020-01-01T00:00:00.000Z');});
test('generic placeholder pages are rejected outside Dayforce too',async t=>{await assert.rejects(extract(t,'<title>Job Details | Jobs</title><meta name="description" content="Find your next adventure">',false,'https://example.org/jobs/1'),/generic careers page/);});
test('generic JSON-LD import remains supported',async t=>{const body=`<script type="application/ld+json">${JSON.stringify({'@type':'JobPosting',title:'Product Designer',hiringOrganization:{name:'Other Company'},description:'Build useful interfaces.',jobLocation:{address:{addressLocality:'Denver'}}})}</script>`;const j=await extract(t,body,false,'https://example.org/jobs/1');assert.equal(j.title,'Product Designer');assert.equal(j.company,'Other Company');assert.equal(j.location,'Denver');});
test('structured country codes are normalized before eligibility checks',async t=>{const body=`<script type="application/ld+json">${JSON.stringify({'@type':'JobPosting',title:'Head of Product Design - Manager role',hiringOrganization:{name:'Super'},description:'Lead a global product design team.',jobLocation:{address:{addressLocality:'',addressCountry:'GB'}}})}</script>`;const j=await extract(t,body,false,'https://www.arbeitnow.co.uk/jobs/companies/super/head-of-product-design-manager-role-407146');assert.equal(j.location,'Outside United States · GB');});
test('Nextdoor Greenhouse wrapper resolves its embedded gh_jid',async t=>{t.mock.method(globalThis,'fetch',async request=>{const url=new URL(typeof request==='string'?request:request.url);assert.equal(url.hostname,'boards-api.greenhouse.io');assert.equal(url.pathname,'/v1/boards/nextdoor/jobs/8140477');return Response.json({id:8140477,title:'Product Designer',company_name:'Nextdoor',location:{name:'Remote · United States'},content:'<p>Design useful neighborhood experiences.</p>',departments:[{name:'Design'}],updated_at:'2026-09-20T00:00:00Z'});});const j=await importJobUrl('https://about.nextdoor.com/careers-list/?gh_jid=8140477',true);assert.equal(j.title,'Product Designer');assert.equal(j.company,'Nextdoor');assert.equal(j.requisitionId,'8140477');assert.equal(j.verification,'employer');});
test('removed Greenhouse postings return a clear availability error',async t=>{t.mock.method(globalThis,'fetch',async()=>new Response('',{status:404}));await assert.rejects(importJobUrl('https://about.nextdoor.com/careers-list/?gh_jid=8140477',true),/no longer available at the employer source/);});
test('wrapper pages discover and resolve their linked ATS posting',async t=>{t.mock.method(globalThis,'fetch',async request=>{const target=typeof request==='string'?request:request instanceof URL?request.toString():request.url;const url=new URL(target);if(url.hostname==='boards-api.greenhouse.io')return Response.json({id:7863636,title:'Staff Product Designer',company_name:'Example Co',location:{name:'Remote - USA'},content:'<p>Design systems for B2B SaaS.</p>',departments:[{name:'Design'}],updated_at:'2026-09-20T00:00:00Z'});return new Response('<html><head><title>Example careers</title></head><body><a href="https://job-boards.greenhouse.io/example/jobs/7863636">View role</a></body></html>',{headers:{'Content-Type':'text/html'}})});const j=await importJobUrl('https://example.org/careers/staff-designer',true);assert.equal(j.title,'Staff Product Designer');assert.equal(j.company,'Example Co');assert.equal(j.url,'https://example.org/careers/staff-designer');assert.deepEqual(j.applicationUrls,['https://job-boards.greenhouse.io/example/jobs/7863636']);});
test('job data embedded in application JSON is extracted without a provider adapter',async t=>{const body=`<script type="application/json">${JSON.stringify({props:{job:{title:'Product Designer',companyName:'Example Co',description:'Design useful interfaces.',location:{name:'Denver, CO'},department:{name:'Design'}}}})}</script>`;const j=await extract(t,body,true,'https://example.org/jobs/1');assert.equal(j.title,'Product Designer');assert.equal(j.company,'Example Co');assert.equal(j.location,'Denver, CO');assert.equal(j.description,'Design useful interfaces.');assert.equal(j.department,'Design');});
test('UltiPro embedded opportunity models import full public job details',async t=>{const body=`<script>var opportunity = new US.Opportunity.CandidateOpportunityDetail(${JSON.stringify({Id:'dc283120-5ac6-46da-8a20-174e74f9f4a5',Title:'UX Design Manager',Locations:[{LocalizedName:'Ohio Remote'}],PostedDate:'2026-08-10T16:50:52.586Z',UpdatedDate:'2026-08-10T16:50:45.239Z',RequisitionNumber:'UXDES006916',Description:'<p>This is a fully remote role for a UX design manager.</p>',JobLocationType:2})});var settings = {"jobBoardName":"Park National Bank Opportunities"};</script>`;const j=await extract(t,body,true,'https://recruiting.ultipro.com/PAR1025PNATB/JobBoard/78198a68-8e94-4f76-b970-3a27214b2ee3/OpportunityDetail?opportunityId=dc283120-5ac6-46da-8a20-174e74f9f4a5');assert.equal(j.title,'UX Design Manager');assert.equal(j.company,'Park National Bank');assert.equal(j.location,'Remote · Ohio Remote');assert.equal(j.requisitionId,'UXDES006916');assert.match(j.description,/fully remote/);assert.equal(j.verification,'employer');});
