import test from 'node:test';
import assert from 'node:assert/strict';
import {importJobUrl} from '../lib/job-import.ts';
const url='https://jobs.dayforcehcm.com/en-US/example/CANDIDATEPORTAL/jobs/2512';
const job={jobPostingId:2512,jobReqId:405,jobTitle:'Senior Designer',jobPostingContent:{jobDescriptionHeader:'<p>About our team</p>',jobDescription:'<p>Lead accessible product design.</p><ul><li>Coach designers.</li></ul>',jobDescriptionFooter:'<p>Equal opportunity employer.</p>'},hasVirtualLocation:true,postingLocations:[{formattedAddress:'United States'}],isoCurrencyRegion:'USD',jobPostingAttributes:[{name:'PayType',value:'Salary'},{name:'HiringMinRate',value:157450},{name:'HiringMaxRate',value:174950}],postingStartTimestampUTC:'2026-09-11T04:00:00Z'};
function html(overrides={}){return `<title>Job Details | Dayforce Jobs</title><script id="__NEXT_DATA__" type="application/json">${JSON.stringify({props:{pageProps:{jobData:{...job,...overrides},dehydratedState:{queries:[{queryKey:['site-info'],state:{data:{clientNamespace:'example',candidateCorrespondenceClientName:'Example Education Talent Team'}}}]}}}})}</script>`;}
async function extract(t,body,strict=false,target=url){t.mock.method(globalThis,'fetch',async()=>new Response(body,{headers:{'Content-Type':'text/html'}}));return importJobUrl(target,strict);}
test('Dayforce extracts complete content and salary from page props',async t=>{const j=await extract(t,html(),true);assert.equal(j.title,'Senior Designer');assert.equal(j.company,'Example Education');assert.equal(j.location,'Remote · United States');assert.equal(j.salaryMin,157450);assert.equal(j.salaryMax,174950);assert.match(j.description,/About our team[\s\S]*Coach designers[\s\S]*Equal opportunity employer/);assert.equal(j.verification,'employer');assert.equal(j.requisitionId,'405');});
test('Dayforce does not infer remote or salary when fields are missing',async t=>{const j=await extract(t,html({hasVirtualLocation:false,postingLocations:[{formattedAddress:'London'}],jobPostingAttributes:[]}));assert.equal(j.location,'London');assert.equal(j.salaryMin,undefined);});
test('Dayforce rejects mismatched IDs and incomplete page data',async t=>{await assert.rejects(extract(t,html({jobPostingId:99})),/complete Dayforce/);await assert.rejects(extract(t,html({jobPostingContent:{}})),/complete Dayforce/);await assert.rejects(extract(t,'<title>Job Details | Dayforce Jobs</title>'),/complete Dayforce/);});
test('Dayforce honors expiry in discovery and preserves explicit manual import',async t=>{const body=html({postingExpiryTimestampUTC:'2020-01-01T00:00:00Z'});await assert.rejects(extract(t,body,true),/expired/);assert.equal((await extract(t,body)).validThrough,'2020-01-01T00:00:00.000Z');});
test('generic placeholder pages are rejected outside Dayforce too',async t=>{await assert.rejects(extract(t,'<title>Job Details | Jobs</title><meta name="description" content="Find your next adventure">',false,'https://example.org/jobs/1'),/generic careers page/);});
test('generic JSON-LD import remains supported',async t=>{const body=`<script type="application/ld+json">${JSON.stringify({'@type':'JobPosting',title:'Product Designer',hiringOrganization:{name:'Other Company'},description:'Build useful interfaces.',jobLocation:{address:{addressLocality:'Denver'}}})}</script>`;const j=await extract(t,body,false,'https://example.org/jobs/1');assert.equal(j.title,'Product Designer');assert.equal(j.company,'Other Company');assert.equal(j.location,'Denver');});

