import {plainText,matchesTargetRole,matchesLocationPreference,type Job,type Profile,type Source} from './model';

function salary(min?:number,max?:number,currency='USD',period='yearly'){if(!min&&!max)return {salary:'Not listed'};const lo=min||max!,hi=max||min!;const annual=/year|annual/i.test(period);const label=annual?`$${Math.round(lo/1000)}k–$${Math.round(hi/1000)}k ${currency}`:`$${lo.toLocaleString()}–$${hi.toLocaleString()} ${currency} / ${period}`;return {salary:label,...(annual&&currency.toUpperCase()==='USD'?{salaryMin:lo,salaryMax:hi}:{})};}
function job(source:Source,raw:{id:string|number;company:string;title:string;location?:string;url:string;description?:string;department?:string;postedAt?:string;salaryMin?:number;salaryMax?:number;currency?:string;salaryPeriod?:string},now:string):Job{return {id:`${source.id}:${raw.id}`,source:source.id,company:plainText(raw.company),title:plainText(raw.title),location:plainText(raw.location||'Not specified'),url:raw.url,description:plainText(raw.description||'').slice(0,45000),department:plainText(raw.department||''),...salary(raw.salaryMin,raw.salaryMax,raw.currency,raw.salaryPeriod),postedAt:raw.postedAt,status:'inbox',reason:'',coverLetter:'',firstSeen:now,lastSeen:now,active:1,origin:'discovery'};}
async function json(url:string){const response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Signal Job Finder/1.0'},signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}. Existing listings were kept.`);if(Number(response.headers.get('content-length')||0)>20000000)throw new Error('This feed is too large to process.');return response.json() as Promise<any>;}
export async function fetchDiscovery(source:Source,profile:Profile){const now=new Date().toISOString();let jobs:Job[]=[];
 if(source.provider==='jobicy'){const data=await json(`https://jobicy.com/api/v2/remote-jobs?count=200&tag=${encodeURIComponent(source.token)}`);jobs=(data.jobs||[]).map((j:any)=>job(source,{id:j.id,company:j.companyName,title:j.jobTitle,location:`Remote · ${j.jobGeo||'eligibility not specified'}`,url:j.url,description:j.jobDescription,department:(j.jobIndustry||[]).join(', '),postedAt:j.pubDate,salaryMin:j.salaryMin,salaryMax:j.salaryMax,currency:j.salaryCurrency,salaryPeriod:j.salaryPeriod},now));}
 if(source.provider==='remoteok'){const data=await json(`https://remoteok.com/api?tag=${encodeURIComponent(source.token)}`);jobs=(Array.isArray(data)?data.slice(1):[]).map((j:any)=>job(source,{id:j.id||j.slug,company:j.company,title:j.position,location:['Remote',j.location].filter(Boolean).join(' · '),url:j.url,description:j.description,department:(j.tags||[]).join(', '),postedAt:j.date,salaryMin:j.salary_min,salaryMax:j.salary_max,currency:'USD'},now));}
 if(source.provider==='arbeitnow'){const pages=await Promise.all([1,2,3].map(page=>json(`https://www.arbeitnow.com/api/job-board-api?page=${page}`)));jobs=pages.flatMap(data=>(data.data||[]).map((j:any)=>job(source,{id:j.slug,company:j.company_name,title:j.title,location:j.remote?`${j.location||'Worldwide'} · Remote`:j.location,url:j.url,description:j.description,department:(j.tags||[]).join(', '),postedAt:j.created_at?new Date(j.created_at*1000).toISOString():undefined},now)));}
 return jobs.filter(j=>j.company&&j.url.startsWith('https://')&&matchesTargetRole(j.title,profile.roles));
}
