import {plainText,salaryFrom} from './model.ts';
import {boundedText} from './bounded-response.ts';
import {dayforceJob} from './dayforce-import.ts';

const headers={'User-Agent':'Mozilla/5.0 (compatible; SignalJobFinder/1.0)','Accept-Language':'en-US,en;q=0.9','Accept':'text/html,application/xhtml+xml'};
function isPrivateHost(hostname:string){const h=hostname.toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h.endsWith('.local')||h.endsWith('.internal')||h==='0.0.0.0'||h==='::1'||/^f[cd][0-9a-f]{2}:/.test(h)||/^fe[89ab][0-9a-f]:/.test(h))return true;const m=h.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);if(!m)return false;const octets=m.slice(1).map(Number);if(octets.some(n=>n>255))return true;const [a,b]=octets;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168);}
export function safeUrl(input:string){const url=new URL(input);if(url.protocol!=='https:'||url.username||url.password||(url.port&&url.port!=='443')||isPrivateHost(url.hostname))throw new Error('Use a public HTTPS job-listing URL.');return url;}
export async function fetchHtml(input:string,allowLinkedIn=true){let url=safeUrl(input);for(let i=0;i<4;i++){if(!allowLinkedIn&&/(?:^|\.)linkedin\.com$/i.test(url.hostname))throw new Error('LinkedIn is manual-only.');const response=await fetch(url,{headers,redirect:'manual',signal:AbortSignal.timeout(18000)});if(response.status>=300&&response.status<400){const next=response.headers.get('location');if(!next)throw new Error('The listing redirected without a destination.');url=safeUrl(new URL(next,url).toString());continue;}if(!response.ok)throw new Error(`The listing returned HTTP ${response.status}.`);const type=response.headers.get('content-type')||'';if(!type.includes('html'))throw new Error('That URL does not appear to be a job-listing page.');if(Number(response.headers.get('content-length')||0)>3000000)throw new Error('The listing page is too large to import.');const html=await boundedText(response,3000000);if(html.length>3000000)throw new Error('The listing page is too large to import.');return {html,url};}throw new Error('The listing redirected too many times.');}
function attr(html:string,key:string,value:string){const patterns=[new RegExp(`<meta[^>]+${key}=["']${value}["'][^>]+content=["']([^"']*)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+${key}=["']${value}["']`,'i')];for(const p of patterns){const match=html.match(p)?.[1];if(match)return plainText(match)}return '';}
function tag(html:string,selector:string){return plainText(html.match(new RegExp(`<${selector}[^>]*>([\\s\\S]*?)<\/${selector}>`,'i'))?.[1]||'');}
function findJobPosting(value:any):any{if(!value)return null;if(Array.isArray(value)){for(const item of value){const found=findJobPosting(item);if(found)return found;}return null}if(typeof value==='object'){if(value['@type']==='JobPosting'||(Array.isArray(value['@type'])&&value['@type'].includes('JobPosting')))return value;for(const item of Object.values(value)){const found=findJobPosting(item);if(found)return found;}}return null;}
function jsonLdJob(html:string){for(const match of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const job=findJobPosting(JSON.parse(match[1]));if(job)return job}catch{}}return null;}
export function applicationLinks(html:string,base:string,structured:any=jsonLdJob(html)){
 const candidates:string[]=[];
 const add=(value:unknown)=>{if(typeof value!=='string')return;try{const u=safeUrl(new URL(value.replace(/&amp;/g,'&'),base).toString());if(!/(?:^|\.)linkedin\.com$/i.test(u.hostname)&&u.toString()!==base)candidates.push(u.toString());}catch{}};
 add(structured?.url);add(structured?.applicationUrl);
 for(const match of html.matchAll(/<a\b([^>]*?)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi)){
  const label=plainText(match[4]);
  if(/apply|application|original (?:job|listing)|company (?:site|website)|employer/i.test(label+' '+match[1]+' '+match[3])||/https:\/\/(?:job-boards\.greenhouse\.io|boards\.greenhouse\.io|jobs\.ashbyhq\.com|jobs\.lever\.co|jobs\.smartrecruiters\.com)\//i.test(match[2]))add(match[2]);
 }
 return [...new Set(candidates)].slice(0,3);
}
function locationText(value:any){if(!value)return '';const list=Array.isArray(value)?value:[value];return list.map(v=>{const a=v?.address||v;return [a?.name,a?.addressLocality,a?.addressRegion,typeof a?.addressCountry==='string'?a.addressCountry:a?.addressCountry?.name].filter(Boolean).join(', ')}).filter(Boolean).join(' · ');}
function structuredSalary(value:any){const q=value?.value||value;if(!q)return {salary:'Not listed'};const min=Number(q.minValue??q.value),max=Number(q.maxValue??q.value);if(!Number.isFinite(min))return {salary:'Not listed'};const unit=String(q.unitText||value?.unitText||'YEAR').toUpperCase();const currency=String(value?.currency||q.currency||'USD').toUpperCase();const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(n);const salary=max&&max!==min?`${money(min)}–${money(max)} / ${unit.toLowerCase()}`:`${money(min)} / ${unit.toLowerCase()}`;return {salary,...(currency==='USD'&&unit==='YEAR'?{salaryMin:min,salaryMax:Number.isFinite(max)&&max?max:min}:{})};}
function safeDate(value:any){if(value===undefined||value===null||value==='')return undefined;const date=new Date(value);return Number.isNaN(date.getTime())?undefined:date.toISOString();}
function linkedinJobId(url:URL){if(!(url.hostname==='linkedin.com'||url.hostname.endsWith('.linkedin.com')))return '';const query=url.searchParams.get('currentJobId');if(query&&/^\d+$/.test(query))return query;const part=url.pathname.split('/').filter(Boolean).at(-1)||'';return part.match(/(?:^|-)(\d+)$/)?.[1]||'';}
function linkedinFields(html:string){return {title:plainText(html.match(/top-card-layout__title[^>]*>([\s\S]*?)<\//i)?.[1]||''),company:plainText(html.match(/topcard__org-name-link[^>]*>([\s\S]*?)<\//i)?.[1]||''),location:plainText(html.match(/topcard__flavor--bullet[^>]*>([\s\S]*?)<\//i)?.[1]||''),description:plainText(html.match(/description__text[^>]*>[\s\S]*?<div[^>]+show-more-less-html__markup[^>]*>([\s\S]*?)<\/div>/i)?.[1]||'')};}
async function greenhouseJob(original:URL){
 const match=original.pathname.match(/^\/([^/]+)\/jobs\/(\d+)/);if(!['job-boards.greenhouse.io','boards.greenhouse.io'].includes(original.hostname)||!match)return null;
 const endpoint=`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(match[1])}/jobs/${encodeURIComponent(match[2])}?content=true`;const response=await fetch(endpoint,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error(`Greenhouse returned HTTP ${response.status}.`);const raw:any=await response.json();const description=plainText(raw.content||'').slice(0,40000);const detected=salaryFrom(description);const company=plainText(raw.company_name||'').trim();const title=plainText(raw.title||'').trim();if(!title||!company)throw new Error('Greenhouse did not return the job title and company.');return {requisitionId:match[2],url:original.toString(),company,title,location:plainText(raw.location?.name||'Not specified'),department:(raw.departments||[]).map((d:any)=>plainText(d.name||'')).filter(Boolean).join(', '),...detected,description,updatedAt:safeDate(raw.updated_at),linkedinUrl:'',linkedinId:''};
}
async function smartRecruitersJob(original:URL){
 if(original.hostname!=='jobs.smartrecruiters.com')return null;
 const oneClick=original.pathname.match(/^\/oneclick-ui\/company\/([^/]+)\/publication\/([^/]+)/i);const standard=original.pathname.match(/^\/([^/]+)\/((?:\d+|[0-9a-f]{8}-[0-9a-f-]{27,36}))(?:-|\/|$)/i);const companyId=oneClick?.[1]||standard?.[1];const postingId=oneClick?.[2]||standard?.[2];
 if(!companyId||!postingId)throw new Error('Signal could not identify the SmartRecruiters company and posting ID from that URL.');
 const endpoint=`https://api.smartrecruiters.com/v1/companies/${encodeURIComponent(companyId)}/postings/${encodeURIComponent(postingId)}`;const response=await fetch(endpoint,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error(`SmartRecruiters returned HTTP ${response.status}.`);const raw:any=await response.json();
 const sections=raw.jobAd?.sections||{};const description=plainText([sections.companyDescription?.text,sections.jobDescription?.text,sections.qualifications?.text,sections.additionalInformation?.text].filter(Boolean).join('\n\n')).slice(0,40000);const title=plainText(raw.name||'').trim();const company=plainText(raw.company?.name||'').trim();if(!title||!company)throw new Error('SmartRecruiters did not return the job title and company.');
 const locationInfo=raw.location||{};const place=plainText(locationInfo.fullLocation||[locationInfo.city,locationInfo.region,locationInfo.country].filter(Boolean).join(', '));const location=locationInfo.remote?['Remote',place].filter(Boolean).join(' · '):locationInfo.hybrid?['Hybrid',place].filter(Boolean).join(' · '):place||'Not specified';const departmentField=Array.isArray(raw.customField)?raw.customField.find((field:any)=>field?.fieldLabel==='Department Name')?.valueLabel:'';const department=plainText(raw.department?.label||raw.department?.name||departmentField||raw.function?.label||'');
 return {requisitionId:postingId,url:original.toString(),company,title,location,department,...salaryFrom(description),description,postedAt:safeDate(raw.releasedDate),linkedinUrl:'',linkedinId:''};
}
export async function importJobUrl(input:string,strict=false):Promise<{url:string;company:string;title:string;location:string;department:string;salary:string;salaryMin?:number;salaryMax?:number;description:string;postedAt?:string;updatedAt?:string;linkedinUrl:string;linkedinId:string;verification?:'employer'|'unverified';validThrough?:string;requisitionId?:string;applicationUrls?:string[]}>{
 const original=safeUrl(input);const greenhouse=await greenhouseJob(original);if(greenhouse)return {...greenhouse,verification:'employer'};const smartRecruiters=await smartRecruitersJob(original);if(smartRecruiters)return {...smartRecruiters,verification:'employer'};const linkedinId=linkedinJobId(original);
 const target=linkedinId?`https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/${linkedinId}`:original.toString();const {html,url:resolved}=await fetchHtml(target,!strict);const dayforce=dayforceJob(html,resolved,strict);if(dayforce)return dayforce;const structured=jsonLdJob(html);
 if(strict&&!structured)throw new Error('No structured job listing found; needs manual review.');
 const validThrough=safeDate(structured?.validThrough);if(strict&&validThrough&&new Date(validThrough).getTime()<Date.now())throw new Error('Listing explicitly expired.');const linked=linkedinId?linkedinFields(html):null;
 const pageTitle=attr(html,'property','og:title')||attr(html,'name','twitter:title')||tag(html,'title')||tag(html,'h1');const title=plainText(structured?.title||linked?.title||pageTitle.split(/\s+[|–—-]\s+/)[0]||'').trim();const company=plainText(structured?.hiringOrganization?.name||linked?.company||attr(html,'property','og:site_name')||pageTitle.split(/\s+[|–—-]\s+/)[1]||'').trim();
 const description=plainText(structured?.description||linked?.description||attr(html,'property','og:description')||attr(html,'name','description')||'').slice(0,40000);const applicantLocation=locationText(structured?.applicantLocationRequirements);const physicalLocation=locationText(structured?.jobLocation);const remote=structured?.jobLocationType==='TELECOMMUTE'||(/\bremote\b/i.test(title)&&!/not remote|hybrid|on[- ]?site/i.test(title));const location=remote?['Remote',applicantLocation||physicalLocation].filter(Boolean).join(' · '):physicalLocation||linked?.location||'Not specified';const detected=structured?.baseSalary?structuredSalary(structured.baseSalary):salaryFrom(description);
 if(/^(job details|job search|careers|career opportunities)$/i.test(title)||/^Find your next adventure[.!]?$/i.test(description))throw new Error('The listing returned a generic careers page instead of job details. Nothing was saved.');
 if(!title||!company||(strict&&/^(unknown|confidential)$/i.test(company)))throw new Error('Signal could not identify the job title and company from that page. Try the employer’s direct listing URL.');
 let employer=false;try{const org=new URL(structured?.hiringOrganization?.url||structured?.hiringOrganization?.sameAs);employer=org.hostname.replace(/^www\./,'')===resolved.hostname.replace(/^www\./,'');}catch{}
 if(['jobs.ashbyhq.com','jobs.lever.co'].includes(resolved.hostname))employer=true;
 return {url:resolved.toString(),verification:employer?'employer':'unverified',validThrough,requisitionId:String(structured?.identifier?.value||''),applicationUrls:applicationLinks(html,resolved.toString(),structured),company,title,location,department:plainText(structured?.occupationalCategory||''),...detected,description,postedAt:safeDate(structured?.datePosted),linkedinUrl:linkedinId?original.toString():'',linkedinId};
}
